import { CATEGORY_INFO } from '@/constants/categories';
import type { Report } from '@/models/report';
import { formatAccuracy, formatCoordinates } from '@/utils/geo';
import { CONFIDENCE_LABEL, formatDateLong, formatPercent, formatTime, SEVERITY_LABEL } from '@/utils/format';
import { escapeHtml } from '@/utils/sanitize';

export const REPORT_DISCLAIMER =
  'This report contains automated visual analysis and should be reviewed by the user before submission. ' +
  'It is a visual assessment, not a legal or engineering determination.';

interface Field {
  label: string;
  value: string;
}

export const reportFields = (r: Report, units: 'imperial' | 'metric'): Field[] => {
  const fields: Field[] = [
    { label: 'Issue', value: CATEGORY_INFO[r.category].label },
    { label: 'Location', value: r.address?.formatted ?? 'Address not available' },
  ];
  if (r.location) {
    fields.push({ label: 'Coordinates', value: formatCoordinates(r.location) });
    fields.push({ label: 'GPS accuracy', value: formatAccuracy(r.location.accuracy, units) });
  }
  if (r.jurisdiction) fields.push({ label: 'Jurisdiction', value: r.jurisdiction.displayName });
  if (r.department) {
    const certainty = r.department.certainty === 'confirmed' ? '' : r.department.certainty === 'likely' ? ' (likely)' : ' (general guidance)';
    fields.push({ label: 'Department', value: `${r.department.name}${certainty}` });
  }
  fields.push({ label: 'Date', value: formatDateLong(r.createdAt) });
  fields.push({ label: 'Time', value: formatTime(r.createdAt) });
  if (r.severity) {
    fields.push({ label: r.severityOverridden ? 'Severity (set by reporter)' : 'Estimated severity', value: SEVERITY_LABEL[r.severity] });
  }
  fields.push({
    label: 'Detection confidence',
    value:
      r.detectionConfidence !== undefined && r.detectionConfidenceLevel
        ? `${CONFIDENCE_LABEL[r.detectionConfidenceLevel]} (${formatPercent(r.detectionConfidence)} model confidence)`
        : 'Not applicable: category chosen by the reporter',
  });
  return fields;
};

export const renderReportText = (r: Report, units: 'imperial' | 'metric'): string => {
  const lines = ['CIVICLENS REPORT', ''];
  for (const f of reportFields(r, units)) lines.push(`${f.label}: ${f.value}`);
  lines.push('', 'Description:', r.description, '');
  if (r.department?.reportingUrl) lines.push(`Official reporting channel: ${r.department.reportingUrl}`, '');
  lines.push(`Important: ${REPORT_DISCLAIMER}`);
  if (r.isDemo) lines.push('', 'DEMO MODE: sample data, not a real observation.');
  return lines.join('\n');
};

/** Printable HTML (rendered to PDF by expo-print). All user text is escaped. */
export const renderReportHtml = (r: Report, units: 'imperial' | 'metric', photoDataUri: string | undefined): string => {
  const rows = reportFields(r, units)
    .map((f) => `<tr><th>${escapeHtml(f.label)}</th><td>${escapeHtml(f.value)}</td></tr>`)
    .join('');
  const demo = r.isDemo ? '<div class="demo">DEMO MODE · Sample data, not a real observation</div>' : '';
  const photo = photoDataUri ? `<img class="photo" src="${photoDataUri}" alt="Evidence photo" />` : '<p class="muted">Photo unavailable.</p>';
  // The title becomes the default file name when a browser saves the page as a PDF.
  const title = `CivicLens report - ${CATEGORY_INFO[r.category].label} - ${r.createdAt.slice(0, 10)}`;
  return `<!doctype html><html><head><meta charset="utf-8" /><title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Roboto, "Helvetica Neue", Arial, sans-serif; color: #111; margin: 0; padding: 28px; }
  h1 { font-size: 13px; letter-spacing: 2px; margin: 0 0 4px; color: #333; }
  h2 { font-size: 22px; margin: 0 0 16px; }
  .demo { background: #efe5ff; color: #5b2ea6; padding: 8px 12px; border-radius: 6px; font-weight: 600; margin-bottom: 14px; }
  .photo { width: 100%; max-height: 420px; object-fit: contain; border-radius: 8px; background: #f2f2f2; }
  table { width: 100%; border-collapse: collapse; margin: 18px 0; font-size: 12.5px; }
  th { text-align: left; width: 34%; color: #555; font-weight: 600; padding: 7px 8px 7px 0; vertical-align: top; border-bottom: 1px solid #e6e6e6; }
  td { padding: 7px 0; border-bottom: 1px solid #e6e6e6; }
  .desc { white-space: pre-wrap; font-size: 13px; line-height: 1.45; }
  .note { margin-top: 20px; padding: 10px 12px; border-left: 3px solid #c08a00; background: #fff8e6; font-size: 11.5px; color: #4a3b00; }
  .muted { color: #777; font-size: 11px; }
</style></head><body>
<h1>CIVICLENS REPORT</h1>
<h2>${escapeHtml(CATEGORY_INFO[r.category].label)}</h2>
${demo}
${photo}
<table>${rows}</table>
<h1>DESCRIPTION</h1>
<p class="desc">${escapeHtml(r.description)}</p>
${r.department?.reportingUrl ? `<p class="muted">Official reporting channel: ${escapeHtml(r.department.reportingUrl)}</p>` : ''}
<div class="note"><strong>Important:</strong> ${escapeHtml(REPORT_DISCLAIMER)}</div>
<p class="muted">Generated by CivicLens. The reporter reviewed and approved this report before sharing.</p>
</body></html>`;
};

export const emailSubject = (r: Report): string =>
  `${r.isDemo ? '[DEMO] ' : ''}Report: ${CATEGORY_INFO[r.category].label}${r.address?.line1 ? ` near ${r.address.line1}` : ''}`;
